"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import addonobject as shared_addonobject
from dataclasses_json import Undefined, dataclass_json
from lago import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AddOns:
    r"""Successful response"""
    
    add_ons: list[shared_addonobject.AddOnObject] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('add_ons') }})  
    