"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from lago import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AppliedAddOnInputAppliedAddOn:
    
    add_on_code: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('add_on_code') }})
    external_customer_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('external_customer_id') }})
    amount_cents: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amount_cents'), 'exclude': lambda f: f is None }})
    amount_currency: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amount_currency'), 'exclude': lambda f: f is None }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AppliedAddOnInput:
    r"""Apply add-on payload"""
    
    applied_add_on: AppliedAddOnInputAppliedAddOn = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('applied_add_on') }})
    