"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import appliedaddonobject as shared_appliedaddonobject
from dataclasses_json import Undefined, dataclass_json
from lago import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AppliedAddOn:
    r"""Successful response"""
    
    applied_add_on: shared_appliedaddonobject.AppliedAddOnObject = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('applied_add_on') }})
    