"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import customerobject as shared_customerobject
from dataclasses_json import Undefined, dataclass_json
from lago import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Customers:
    r"""Successful response"""
    
    customers: list[shared_customerobject.CustomerObject] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('customers') }})
    