"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import planobject as shared_planobject
from dataclasses_json import Undefined, dataclass_json
from lago import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Plan:
    r"""Successful response"""
    
    plan: shared_planobject.PlanObject = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('plan') }})  
    