"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import subscriptionobject as shared_subscriptionobject
from dataclasses_json import Undefined, dataclass_json
from lago import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Subscriptions:
    r"""Successful response"""
    
    subscriptions: list[shared_subscriptionobject.SubscriptionObject] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('subscriptions') }})  
    