"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import appliedcouponobject as shared_appliedcouponobject
from dataclasses_json import Undefined, dataclass_json
from sdk import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AppliedCoupons:
    r"""Successful response"""
    
    applied_coupons: list[shared_appliedcouponobject.AppliedCouponObject] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('applied_coupons') }})  
    