"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import addon as shared_addon
from ..shared import apiresponsenotfound as shared_apiresponsenotfound
from ..shared import apiresponseunauthorized as shared_apiresponseunauthorized
from typing import Optional


@dataclasses.dataclass
class DestroyAddOnRequest:
    
    code: str = dataclasses.field(metadata={'path_param': { 'field_name': 'code', 'style': 'simple', 'explode': False }})
    r"""Code of the existing add-on"""  
    

@dataclasses.dataclass
class DestroyAddOnResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    add_on: Optional[shared_addon.AddOn] = dataclasses.field(default=None)
    r"""Successful response"""  
    api_response_not_found: Optional[shared_apiresponsenotfound.APIResponseNotFound] = dataclasses.field(default=None)
    r"""Not Found error"""  
    api_response_unauthorized: Optional[shared_apiresponseunauthorized.APIResponseUnauthorized] = dataclasses.field(default=None)
    r"""Unauthorized error"""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    