"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import apiresponsenotallowed as shared_apiresponsenotallowed
from ..shared import apiresponsenotfound as shared_apiresponsenotfound
from ..shared import apiresponseunauthorized as shared_apiresponseunauthorized
from ..shared import subscription as shared_subscription
from typing import Optional


@dataclasses.dataclass
class DestroySubscriptionRequest:
    
    external_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'external_id', 'style': 'simple', 'explode': False }})
    r"""External ID of the existing subscription"""
    

@dataclasses.dataclass
class DestroySubscriptionResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    api_response_not_allowed: Optional[shared_apiresponsenotallowed.APIResponseNotAllowed] = dataclasses.field(default=None)
    r"""Not Allowed error"""
    api_response_not_found: Optional[shared_apiresponsenotfound.APIResponseNotFound] = dataclasses.field(default=None)
    r"""Not Found error"""
    api_response_unauthorized: Optional[shared_apiresponseunauthorized.APIResponseUnauthorized] = dataclasses.field(default=None)
    r"""Unauthorized error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    subscription: Optional[shared_subscription.Subscription] = dataclasses.field(default=None)
    r"""Successful response"""
    